version: '3'
services:
  nagios4:
    environment:
      NAGIOSADMIN_USER: "admin"
      NAGIOSADMIN_PASS: "nagiosadmin"
      TZ: "Europe/Madrid"
    image: manios/nagios:latest
    ports:
      - "8080:80"
    volumes:
      - "./etc/:/opt/nagios/etc/"
      - "./var:/opt/nagios/var/"
      - "./ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./custom-plugins:/opt/Custom-Nagios-Plugins"
